### **패키지**


파이썬 패키지는 파이썬 코드를 모듈화하고 재사용 가능한 형태로 구성하는 방법입니다.

패키지는 여러 모듈의 집합이며, 관련된 기능을 그룹화하여 제공합니다.

이를 통해 코드를 구조화하고 관리하기 쉽게 만들어줍니다.

파이썬 외부패키지 별로 없음

아나콘다(개발자용) 외부패키지 많음

- 많으면 다양하지만, 설치가 길고 무겁고
- 적으면 원하는 것만 설치해서 사용 가능

= 장단점이 있음

### **패키지 설치**

- 단일 패키지 설치

pip install package_name

- 특정 버전의 패키지 설치:

pip install package_name==version_number

- 가상환경에 패키지 설치:

가상환경 생성

python -m venv myenv

가상환경 활성화

source myenv/bin/activate   /  윈도우의 경우: .\myenv\Scripts\activate

패키지 설치

pip install package_name

가상환경 비활성화

deactivate




### **python**

패키지(모듈) 설치 pip install ~~

import pandas

import numpy

In [6]:
#1. 1부터 10까지(미포함)의 2걸음 크기의 정수값 배열을 생성해보자

import numpy as np  ## 항상 제일 먼저

arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [4]:
#2. 모양이 (3,4)인 모든 값이 1인 배열을 생성해보자

ones_1d = np.ones((3,4))  # 모양은 2차원, 3행 4열
print(ones_1d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
#3. 0과 1사이를 10등분하고자 할 때 등분값 배열을 생성해보자

arr2 = np.linspace(0,1,10)
print(arr2)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [7]:
# 답
arr3 = np.linspace(0,1,11)
arr3

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [22]:
# A 행렬 생성

A = np.array([[ 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]])


<function shape at 0x7e0a87f89d80>
19
1 6


In [23]:
# A의 모양 추출
A.shape

(5, 5)

In [24]:
# 19 값 추출

A[3,3]

19

In [31]:
# 슬라이싱을 이용하여 [[1, 2], [6, 7]] 값을 추출

A[0:2, 0:2]

array([[1, 2],
       [6, 7]])

In [32]:
A[:2, :2]

array([[1, 2],
       [6, 7]])

In [35]:
# 슬라이싱을 이용하여 [[19, 20], [24, 25]] 값을 추출

A[3: , 3:]

array([[19, 20],
       [24, 25]])

In [36]:
# 슬라이싱을 이용하여 0축의 첫 번째 행과 두 번째 행을 추출 = 잘 모르겠음

# 0축 - 2차원 개념에선, A[0]은 첫번째 행 A[1]는 2번째 행
# 축 - 행열 타 표현

A[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [37]:
# 슬라이싱을 이용하여 1축의 마지막 열과 마지막 직전 열을 추출 = 잘 모르겠음

A[:, -2:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

In [38]:
# A 행렬 생성
# 3차원임

A = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9,10, 11, 12]],
              [[13, 14, 15, 16],
               [17, 18, 19, 20],
               [21, 22, 23, 24]],
              [[25, 26, 27, 28],
               [29, 30, 31, 32],
               [33, 34, 35, 36]]])

In [41]:
# A 배열의 모양과 크기 출력

print(A.shape)
print(A.size)

(3, 3, 4)
36


In [42]:
# A 모양을 (3,4,3)으로 변경

A.reshape(3,4,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [45]:
# A를 1차원 배열로 구성

print(A.flatten())

## print 붙이면 쉼표가 없고
## 그냥 출력하면 쉼표가 잇음

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [50]:
# A 행렬 생성

arr = np.arange(1, 37)

arr_3d=arr.reshape(3,3,4)

arr_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])